### ISSUE TITLE
Milk item bugs the inventory

### ISSUE THREAD

**Issue by 0xCiBeR** [NullSystemWorks/mtadayz#10]
As the title says, pickup or just add a Milk elementData and inventory gets bugged.

**Comment by 1B0Y** [comment]
Anything in debug?

**Comment by dreezyduh** [comment]
Check language_gear.lua line 3306 it should be {"Can (Milk)", 1, "Item"},

**Comment by mtadayz** [comment]
Fixed, will be in my next commit.
