### ISSUE TITLE
Periodic Error in console

### ISSUE THREAD

**Issue by WyattParker** [NullSystemWorks/mtadayz#103]
When no one is on the server, periodically, these errors do show up in the console:

WARNING: DayZ\init\loot\other_loot.lua:29: Bad argument @ 'getElementData' [Expected element at argument 1]
WARNING: DayZ\init\loot\other_loot.lua:29: Bad argument @ 'destroyElement' [Expected element at argument 1, got boolean]
WARNING: DayZ\init\loot\other_loot.lua:30: Bad argument @ 'destroyElement' [Expected element at argument 1]

**Comment by 1B0Y** [comment]
Gonna have a quick look into it now before I head out :D

**Comment by mtadayz** [comment]
Fixed as of commit  	be9eb6d.
