### ISSUE TITLE
Slothbot Warning

### ISSUE THREAD

**Issue by WyattParker** [NullSystemWorks/mtadayz#104]
I've noticed this is appearing in the console
WARNING: slothbot\sbserver.lua:865: Bad argument @ 'giveWeapon' [Expected element at argument 1]

I haven't noticed a pattern in regards to it.

**Comment by 1B0Y** [comment]
This usually occurs when slothbot tries to give a weapon to a bot, even though the bot was only **just** destroyed. Let us know if it continues and we'll throw some debug code in there ;)

**Comment by WyattParker** [comment]
Will do! Thanks for the reply :)

**Comment by 0xCiBeR** [comment]
Any updates on this?

**Comment by WyattParker** [comment]
Yes, it appeared again a few hours ago
[2017-06-04 23:19:45] WARNING: slothbot\sbserver.lua:865: Bad argument @ 'giveWeapon' [Expected element at argument 1]
