### ISSUE TITLE
Painkillers, Morphine, and Broken legs

### ISSUE THREAD

**Issue by WyattParker** [NullSystemWorks/mtadayz#105]
Painkillers do not stop the screen wobble until you relog

Morphine does not allow jumping/sprinting until relog.

Dying with a broken leg does not reset the broken leg, meaning, even after death with a broken leg, you still cannot sprint or jump

(NOTE: If these were supposed to be separate issues, I apologize. I just felt since they were all medical and similar, it could all be one issue)

**Comment by mtadayz** [comment]
Should be fixed with the latest commit.
