### ISSUE TITLE
Down But Not Out

### ISSUE THREAD

**Issue by mtadayz** [NullSystemWorks/mtadayz#109]
Just a spontaneous suggestion I'm throwing in here. If you get shot by a weapon that does not mean instadeath (which means not a sniper), you won't die immediately, you enter a "Down But Not Out" state. It's similiar to being unconscious, only that you can still use your inventory to, for instance, heal yourself. Another shot/hit will kill you, though.

**Comment by GribixTugaZ** [comment]
Seems like a cool idea.To make it even better it should be something random.

**Comment by mtadayz** [comment]
I'll probably do it via a hidden stat called "determination", which increases the longer you survive and the more humanity you have (meaning being a hero is more rewarding).

**Comment by mtadayz** [comment]
I'm closing this issue, as this will be integrated into issue #133.
