### ISSUE TITLE
Achievements get bugged after the first time you earn them

### ISSUE THREAD

**Issue by dreezyduh** [NullSystemWorks/mtadayz#11]
For example if you earn the "Kill one zombie" achievement and die you can't earn it again (I don't know if this is intentionally).
I fixed this by adding `elseif data[1] =="achievements" then setElementData(player,data[1],false)` to the spawn_init.lua when the player gets starting equipment

**Comment by neves768** [comment]
Achievements works for account not per life (like Steam achievements)

**Comment by dreezyduh** [comment]
Thanks for making it clear
