### ISSUE TITLE
Any bugs found

### ISSUE THREAD

**Issue by Furzymta** [NullSystemWorks/mtadayz#110]
Hi , 

I found 3 bugs

First bug

When u click fast in left-button ( mouse ) the sniper burst fire, ( like M4 )

2

When u fire with sniper and press q or e fast ( qs ) when u back to the hand u stay with 0 ammo in clip
( you have to re-equip in inventory )

3 - The new weapons system is not serverside
For example i have M24 Equiped

The other player doenst have weapon , He see Main sniper in my Hand ( GTA SA SNIPER )
this bug is for Sniper, m4 , ak..

The player just see my weapon skin when he equip the same weapon..

That's it.

Thank you, ( I'm opening a server with this GM , i can't solve this bugs )

**Comment by mtadayz** [comment]
1. Acknowledged.
2. Will try to replicate that.
3. That's not a bug, it's just the way the code handles different weapons which happen to have the same weapon ID (for instance, the DMR and CZ550 have the same original model, namely the sniper).

**Comment by Furzymta** [comment]
Hi guys, i solved the bug , i set 10 ammo in clip with setWeaponProperty 

and i did simple script to block shots for time
with toggleControl("fire") and setTimer. it's okay for me , 

thanks.
