### ISSUE TITLE
Some skins produce frame drops

### ISSUE THREAD

**Issue by dreezyduh** [NullSystemWorks/mtadayz#111]
Like setting the skin to id 1 or 28 don't show the skin and start stuttering every 3 sec(ish)

**Comment by mtadayz** [comment]
How exactly did this happen, i.e what did you do to cause those frame drops?

**Comment by dreezyduh** [comment]
When I set the skin id some models change and the other that don't change start stuttering like there's a timer that checks for the model. I stopped the dayz resource , tried to change my skin again and it worked so I think it got smth to do with the resource. I have the last dayz version from here

**Comment by mtadayz** [comment]
I'm afraid that this is no bug, but rather you not changing the necessary functions to make whatever you want to do work. I recommend skimming through the script again, most of the skin-related functions are found inside the players folder.
