### ISSUE TITLE
Bug skin AKM and binoculars

### ISSUE THREAD

**Issue by ForyouL** [NullSystemWorks/mtadayz#112]
Equipping **AKM** and **Binoculars**, the akm skin looks just like in the picture:

![mta-screen_2017-07-18_12-05-07](https://user-images.githubusercontent.com/30216337/28324804-ab654b88-6bb2-11e7-8473-60f682f280b0.png)
![mta-screen_2017-07-18_12-05-09](https://user-images.githubusercontent.com/30216337/28324806-ab6af984-6bb2-11e7-8c16-d49b5c797374.png)
![mta-screen_2017-07-18_12-05-11](https://user-images.githubusercontent.com/30216337/28324807-ab6fb690-6bb2-11e7-8273-bf8d11ae82d2.png)
![mta-screen_2017-07-18_12-05-12](https://user-images.githubusercontent.com/30216337/28324805-ab670a72-6bb2-11e7-8e03-3d6dca4c4736.png)
![mta-screen_2017-07-18_12-05-15](https://user-images.githubusercontent.com/30216337/28324808-ab7303c2-6bb2-11e7-93f5-5da60161f66a.png)

**Comment by mtadayz** [comment]
That's normal and due to the way weapon skins are coded.
