### ISSUE TITLE
Maybe an error - Helicrash loot

### ISSUE THREAD

**Issue by ForyouL** [NullSystemWorks/mtadayz#113]
I'm not sure if it was intentional or if it really is a mistake. 
There is a lot of gear next to the helicrash

some images:
![mta-screen_2017-07-20_20-39-47](https://user-images.githubusercontent.com/30216337/28443329-ba9e7a72-6d8b-11e7-97c5-f7d9a077479e.png)
![mta-screen_2017-07-20_20-39-50](https://user-images.githubusercontent.com/30216337/28443330-ba9f0992-6d8b-11e7-97f7-f9d8d9d443e8.png)
![mta-screen_2017-07-20_20-39-54](https://user-images.githubusercontent.com/30216337/28443332-baa4623e-6d8b-11e7-9435-2b08f465a8ca.png)
![mta-screen_2017-07-20_20-40-02](https://user-images.githubusercontent.com/30216337/28443331-ba9f756c-6d8b-11e7-9449-9b44285f6d97.png)
![mta-screen_2017-07-20_20-52-57](https://user-images.githubusercontent.com/30216337/28443602-85119bbc-6d8d-11e7-95d1-349ee8f1a6a3.png)

**Comment by neves768** [comment]
Thanks for your report, we'ill check this as soon as possible.

- Null System Works

**Comment by mtadayz** [comment]
This is done on purpose. There was, however, another bug related to the helicrash sites, which has been fixed with commit  9ca5de1.
