### ISSUE TITLE
Bug Brokenbone 'Morphine dont use' gm 0.9.9a 

### ISSUE THREAD

**Issue by jdmNTC** [NullSystemWorks/mtadayz#116]
When the player die and in the mean time breaks his leg, when he respawn he can not run and also the broken bone icon does not appear

**Comment by neves768** [comment]
Can you provide more informations? Video or screenshots are acceptable. I'ill be working on it.

**Comment by jdmNTC** [comment]
here, I made a video showing 2 problems in 'gm' 0.9.9a https://youtu.be/cQtpq7ns5Os

**Comment by jdmNTC** [comment]
if possible help me solve it as I have already edited the gamemode a lot so I can open my server there ..

**Comment by KOPYk4T** [comment]
Download the last version, it is solved to me

**Comment by KOPYk4T** [comment]
https://github.com/ciber96/mtadayz/commit/491395be5a3aaf9eff727d6e8163fc6aeb0a977f

**Comment by jdmNTC** [comment]
I can not download a new one because I have already packed many details in this 'gamemode'
if I have to change the 'gm' I will stop playing.

**Comment by jdmNTC** [comment]
and yes my gamemode is the most updated

**Comment by jdmNTC** [comment]
how can you see: https://imgur.com/a/Any2x

**Comment by jdmNTC** [comment]
Does this 'link' above solve my problem? @DaveSticks

**Comment by 0xCiBeR** [comment]
Sorry we don't support old versions of the gamemode. Please refer to the commits page and find the commit that solves your issue so you can merge that!
