### ISSUE TITLE
Add currency

### ISSUE THREAD

**Issue by ghost** [NullSystemWorks/mtadayz#117]
Add currency, for donat, that you could buy transport, items + panel donats

**Comment by neves768** [comment]
We'ill elaborate something cool. Thanks for your suggestion =)

**Comment by ghost** [comment]
If you develop this donation system, I thenk and put your copyright as an advertisement, as I plan to launch a major project in Russia

**Comment by mtadayz** [comment]
There's no need for currency. If you wish to add one, you can do so yourself, there's plenty of resources and scripts which accomplish just that.
