### ISSUE TITLE
Bug, the game stucks every 1 second (FPS drop)

### ISSUE THREAD

**Issue by KOPYk4T** [NullSystemWorks/mtadayz#119]
I've read that another people also have this problem. When I start DayZ the game stucks for 1 sec every second, making imposible playing and aiming.

Oh, and it get worst when the time go forward. After 30 mins, its imposible to play. A lot of people have this problem

It's like a timer bug, like if the gamemode is checking something every second and it lags the game

I thought that it was another resource, but then i started only DayZ, and still laggy with this FPS drop

**Comment by KOPYk4T** [comment]
It's something related to loot i think. My server started with a weight of 5.5 mb, and after 3 hours it was like 11.6 mb to enter

**Comment by KOPYk4T** [comment]
Oh, and i tried another servers with this version and they also have this problem.

Then i created a local server, with another DayZ Gamemode (older ones, like 2 years old) and it did'nt have this problem

**Comment by jdmNTC** [comment]
This problem does not happen to me. I use the '0.9.9a'.
The only problem that occurred was when using the 'item morphine'

**Comment by neves768** [comment]
We have been studying this case for a long time by now. We couldn't find what causes this problem, but we are still trying to find it. 
**Any help coming from the community is very welcome.**

**Comment by KOPYk4T** [comment]
About the increasing weight of the server: I think that it is the item respawn. Because i let it 2 hours and it increased now from 5mb to 7.5 mb and it doesn't stop

**Comment by KOPYk4T** [comment]
I've found the error.

I've been deleting a lot of the code in the meta.xml to discard where it was the problem

And the problem is in one of this:

	<script src="handlers/world/client/night/c_night.lua" type="client" cache="false" />
	<file src="handlers/world/client/night/mta-helper.fx" type="client" />
	<file src="handlers/world/client/night/night.fx" type="client" />

**Comment by KOPYk4T** [comment]
Like i said, it was checking every second if it was on night or not. That was lagging.

I changed 1 sec in c_night.lua to 5 mins

**Comment by ghost** [comment]
Since night and day are periodic events, is it really necessary to check for it every second?

**Comment by Risusama** [comment]
I'll make a change soon in my repo and create a pull request for it. For starters, I'll set it to 5 minutes. Plus, I'll also make it easily configurable.

**Comment by jdmNTC** [comment]
Were you able to solve the problem?
Can I do it with my gamemode so I do not suffer too?

**Comment by godzera** [comment]
Did you just delete the 'goal' and stop the 'lag'?

**Comment by jdmNTC** [comment]
Did you just delete the 'meta' and stop the 'lag'?

**Comment by DaveSticks** [comment]
No no. Go to: 

<script src="handlers/world/client/night/c_night.lua" type="client" cache="false" />

And then find this:

			`end,1000,0,clone)`

and this:

		`nightTimer = setTimer(night_check, 1000, 0)`

Set the 1000's to 300000 and problem solved.

**Comment by KOPYk4T** [comment]
<script src="handlers/world/client/night/c_night.lua" type="client" cache="false" />

Find that file, and then find this line...
			**end,1000,0,clone)**
and this one...
**nightTimer = setTimer(night_check, 1000, 0)**
Now you have to change the 1000 for a 300000 like this...
**end,300000,0,clone)**
**nightTimer = setTimer(night_check, 300000, 0)**

**Comment by neves768** [comment]
Pull request #120 should fix this problem.

**Comment by neves768** [comment]
@debexeL @DaveSticks Is this bug still a thing? Did it got fixed?

**Comment by Risusama** [comment]
This has been fixed in #120 .
