### ISSUE TITLE
[Achievements] New achievements needed

### ISSUE THREAD

**Issue by neves768** [NullSystemWorks/mtadayz#12]
> Achievements

We need suggestions for achievs and collaboration with icons design.

**Comment by dreezyduh** [comment]
Finding a big backpack maybe, pitch a tent, make a campfire,  help someone by healing them(like bandage someone for the 1st time or the 50th time) . I will try to make some icons if no one else offers to.

**Comment by mtadayz** [comment]
- Waste Of Time (1-3): Play for X hours without logging off/dying
- Oh, Shiny! (1-10): Loot X loot piles
- Emergency Room: Visit a hospital (= loot a hospital box)
- Litterbug: Loot 5 "Empty Tin Cans"
- Not Cannibalism (1-3): Eat X amount of meat
- The Hunter: Kill an animal and take its meat
- Sniper (1-4): Kill a player from over X meters
- Doctor Without Borders: Heal another player with a blood bag
- I Can See My House From Here!: Fly with a heli/plane or climb a mountain (= z-axis coordinate is >=100)
- Firestarter: Light a fire (Wood Pile + Box of Matches)

**Comment by dreezyduh** [comment]
So after testing it for a bit I've seen that if I die after having any achievement , when I respawn there is nothing in my journal in the achievements tab and can't unlock them ever again on this acc (https://imgur.com/JIxGhvI I hope this doesn't happen only to me.

**Comment by neves768** [comment]
@dreezyduh investigating it...
* EDIT: should be fixed in #16 pull request

**Comment by neves768** [comment]
should be fixed in #16 pull request
