### ISSUE TITLE
Painkiller bug

### ISSUE THREAD

**Issue by KOPYk4T** [NullSystemWorks/mtadayz#122]
Painkillers are not working, the shake don't stop if u use it in a car

**Comment by jdmNTC** [comment]
funny. have to stay disconnected right?

**Comment by Risusama** [comment]
From what I understand, this has already been fixed months ago. Download the latest version from https://github.com/NullSystemWorks/mtadayz/archive/master.zip
Though, as you mentioned "if you use it in a car", I am not 100% sure if this is the same bug as in issue #105.

**Comment by mtadayz** [comment]
Nah, that one is really a bug, I can confirm it. However, I think I fixed it with commit e978f50. So I'll close this issue for now.
