### ISSUE TITLE
Adding loot spawns question

### ISSUE THREAD

**Issue by KOPYk4T** [NullSystemWorks/mtadayz#126]
Hi, i have a question about how i can add loot spawns.

I added some loot spawns in the cfgLoot.lua but it didn't worked there is no new loot... just the same

Love if you can help me or fix it

**Comment by mtadayz** [comment]
Every lootpoint has a chance to not contain any loot, this is to bring some variety into lootpoints.

init/loot/world_loot.lua is the file where those chances are being calculated. The actual code for that starts with this function: createPickupsOnServerStart. If you want to create your own lootpoints which spawn 100% of a time, I suggest you either write your own code or alter the existing one accordingly.
