### ISSUE TITLE
[Important bug] fracturedLegs & fracturedArms bug - Last Version

### ISSUE THREAD

**Issue by KOPYk4T** [NullSystemWorks/mtadayz#130]
When i get shot in the leg, or in the arms i can't use morphine. Is this part of the GM or a bug?

**Comment by KOPYk4T** [comment]
I noticed that only happens when you get shot in the leg. If u got shot in the arms you can use morphine, if u got shot in the legs, you can't use morphine

**Comment by KOPYk4T** [comment]
And yeah, i have the last version, i haven't modified nothing

**Comment by mtadayz** [comment]
Hopefully fixed as of commit 9ca5de1.
