### ISSUE TITLE
RPG Elements

### ISSUE THREAD

**Issue by mtadayz** [NullSystemWorks/mtadayz#133]
I'd like to add some RPG elements to DayZ. Seeing as the gamemode is kind of dead, we should think about adding something fresh and a unique twist to the whole thing.
My idea is as follows:

Players gain XP by surviving, killing zombies/players, helping other players, completing jobs given by NPCs, etc.  There's no direct level-up involved - once a player has enough XP, he/she can commit some of it into skill points. Once converted, the player can use the acquired SP and put them into a skill (with the XP needed for conversion to SP steadily increasing). 

**CLASSES**
At "launch", we'd offer 4 classes: Medic, Soldier, Scavenger & Engineer. Whether or not the player has to stick to one class is open to debate. Personally, I think we should add a pool of sorts - investing XP into that pool allows you to select a skill from another class (although the conversion rate would be cut by half).

**SKILLS**
So far, I've worked out these skills for each class:

**Medic**:
- Second Chance: x% chance to survive an otherwise fatal hit (passive, cooldown: 600 seconds)
- Medical Proficiency: x% healing power for you and other players (passive)
- Without Borders: Players within vicinity will have increased blood regen by x% (active, duration: 10s+10s*skill level)

**Soldier**:
- Weapon Proficiency: Flat weapon damage increase (passive)
- Toughness: Flat damage reduction (passive)
- Critical Shot: x% chance to deal critical damage (active, damage*2, duration: 30s, cooldown: 60 seconds)

**Scavenger**:
- Camouflage: Blend in with your surroundings while standing still (passive, setElementAlpha decrease)
- Dodging Blows: x% chance to dodge zombie/weapon hits (active, duration: 5s+5s*skill level)
- ?

**Engineer**:
- Ammo Efficiency: x% chance to not consume ammo when shooting (passive)
- ?
- ?

If you have more suggestions as to which skills could be added, feel free to post them here.

**What happens if a player dies?**
All skills will be retained. However, the player loses all XP and SP he may have accumulated.

**What if the server had to be reset?**
Skills info will be saved in an extra database. If the server has been reset and you lost all your items, you will still keep your skills as long as you register with the same name you used prior to the reset (which is usually the case).

If you have any questions, ask them here. For now, I'll start with coding the base.

**Comment by Risusama** [comment]
I like the idea! But, perhaps the conversion rate you talked about, should lower by itself as you gain levels, making it a little harder to get all the skills?

And I also have an idea for one Engineer skill.
- Explosion resistant kevlar vest: Maximum of 3 levels. First level is 10% explosion resistance. Second level equals first level (10%) + half of first level (5%) = 15% explosion resistance. Third level would equal second level (15%) + half of second level (7.5%) = 22.5% explosion resistance.

**Comment by mtadayz** [comment]
Yeah, sorry, I corrected a mistake on my part. Obviously, you'll need more XP the more you convert. 
I like the skill, though it's a bit...situational, because explosions rarely occur in MTA DayZ. Most of the time, you die due to some bullet between your eyes. Maybe I'll disable the engineer class until we have some skills to work with.

**Comment by Risusama** [comment]
I have another idea for Engineer skill.

###EDIT###
Jesus Tape: 15% chance to repair vehicle by 25% of current vehicle health if it [current vehicle health] is at least 30% of maximum health, or by 35% of current vehicle health if it [current vehicle health] is less than 30% of maximum health. (passive, no extra levels, 45 minute cooldown (Real-Time))

###ORIGINAL IDEA###
Jesus Tape: 15% chance to repair vehicle by quarter of current vehicle health (passive, no extra levels, 45 minute cooldown (Real-Time))

**Comment by mtadayz** [comment]
I like that one. Will add it to the list.

**Comment by mtadayz** [comment]
Update:
Here's how the GUI's looking so far.
![mta-screen_2018-02-24_17-24-46](https://user-images.githubusercontent.com/14334938/36632507-c4c67dda-1987-11e8-87c1-3bac2a0768ee.png)

In order to activate skills, you have to activate a "path" first. There are 4 paths: Soldier, Medic, Scavenger, Engineer. Clicking on their respective icon will consume one SP, and the path is open. 

Advancing towards the next level of a skill will always consume 1 SP, regardless of its level. However, in order to actually get SP, you'll have to convert XP to SP, and only one is generated each time you click on "Convert XP to SP". Each conversion requires more XP.

The Skills page is integrated into the journal. A description of the skill is provided whenever you point your cursor to the skill in question, along with the current chance for it trigger. All skills are currently passive, though I plan on adding active skills as well.

Stay tuned, the RPG update will be coming soon.

**Comment by neves768** [comment]
Awesome feature =)

**Comment by mtadayz** [comment]
Added with commit  5f60e0b. Please post feedback etc. in issue #158.
