### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by waghcwb** [NullSystemWorks/mtadayz#137]
I think the project needs a better documentation about all game aspects and development things.

Currently, if I'm new to MTA, looking only on the Github repository, I do not know where to start and where to go and how to help (looking on issues tab works only for advanced users).

**Comment by mtadayz** [comment]
While I agree on the "improve documentation" part, I don't think someone new to MTA should look at the jumbled and messed up code that DayZ is consisting of. It's way too confusing if you're not familiar with Lua or MTA in general. As such, a "newbies guide" is a terrible idea, and only serves to make people ask questions akin to "how do I change X?". Long story short: you're only helpful if you have some experience under your belt.
I'll try to clean up some of the code over the next few months, whenever I have the time to do that. Closing this issue for now, but will keep that in mind.
