### ISSUE TITLE
Standard_female.txd - Wrong texture

### ISSUE THREAD

**Issue by Risusama** [NullSystemWorks/mtadayz#141]
File "/DayZ/models/players/txd/standard_female.txd" has textures for a male instead of a female.

As @ciber96 said - it should be sufficient to mark this as a bug for now, and later correcting the texture.

###EDIT###
![Image of the problem](https://user-images.githubusercontent.com/12206978/35722756-358d1a7c-0800-11e8-8820-2e844f75d071.png)

**Comment by 0xCiBeR** [comment]
Flagged

**Comment by mtadayz** [comment]
Thing is, since male/female options are currently not working, the question arises as to whether or not we should reimplement gender or scrap that altogether.

**Comment by Risusama** [comment]
Well, I think we should at least remove the wrong model/texture. I don't think removing the gender selection would a bad idea either. I seldom saw people using the possibility anyway (if it ever even worked). I can do the removal of the model/texture.

**Comment by mtadayz** [comment]
Removed and therefore fixed as of commit  6c15361.
