### ISSUE TITLE
Vehicles not working

### ISSUE THREAD

**Issue by lyricalmm** [NullSystemWorks/mtadayz#153]
Vehicles are not spawning, I tried to resolve this problem but I couldn't. Vehicles on F7 Panel are not showing or spawning.
Any help here? :)

**Comment by dreezyduh** [comment]
this bug has been fixed some time ago, here are the steps
delete vehicles.db inside the databases folder
stop DayZ, delete vehicleManager from the console (delaccount vehicleManager), then start DayZ again

**Comment by lyricalmm** [comment]
@dreezyduh I did that, but now in console says 
`ERROR: DayZ/init/vehicles/vehicles_init.lua:266: bad argument #1 to ' [ ipairs' (table expected, got nil)`

**Comment by dreezyduh** [comment]
have you tried restarting the server? also, did you modify anything in the script ?

**Comment by lyricalmm** [comment]
I tried 3 times, with the default script. I have also downloaded the 0.9.9a, do I need to download the other one version? :)

**Comment by dreezyduh** [comment]
I haven't tried this with the newer versions, I'll try to do it rn see if I have the same problem

**Comment by lyricalmm** [comment]
What version do you use?

**Comment by dreezyduh** [comment]
I'll get the master

**Comment by lyricalmm** [comment]
Will this work on version 0.9.6a ?

**Comment by mtadayz** [comment]
From that error you posted, I can infer that something is wrong with the vehicle spawning itself, not the database. Are you sure you didn't edit cfgVehicles.lua in some way? Because it looks like you did, but failed to do so properly.

**Comment by mtadayz** [comment]
As it's been a while since the original poster said something about this issue, I consider this issue closed.
