### ISSUE TITLE
Problem loading weapons skins [BUG] 0.9.9.1a

### ISSUE THREAD

**Issue by stickMen** [NullSystemWorks/mtadayz#155]
I found this little bug now. How can we fix it ??
![mta-screen_2018-02-22_15-16-44](https://user-images.githubusercontent.com/36742456/36556498-245d598a-17e4-11e8-8bc5-278199cad700.png)

**Comment by 0xCiBeR** [comment]
Please download https://github.com/NullSystemWorks/mtadayz/archive/master.zip and use that, let us know if the error continues on that version.

**Comment by stickMen** [comment]
This version Neves passed me yesterday my friend '-'

**Comment by mtadayz** [comment]
I fixed the "night_c.lua" bug, however, I am unable to replicate the M24 bug. Did you change the weapon model?

**Comment by neves768** [comment]
@mtadayz He said that it was his mistake.
