### ISSUE TITLE
HUD PROBLEM IN THE INVENTORY

### ISSUE THREAD

**Issue by godzera** [NullSystemWorks/mtadayz#156]
(Before everything. I did not change anything)
This is happening in the latest version.
When you equip your weapon in the inventory where it says "holding" should appear the weapon, but it is not appearing!
![mta-screen_2018-03-01_22-24-42](https://user-images.githubusercontent.com/36976165/36879854-76f57946-1da4-11e8-95eb-f3f5fe316dfb.png)

**Comment by mtadayz** [comment]
Yep, that's due to the switch from elementData to tables for status information (such as blood, hunger/thirst, weapons...). I haven't gotten around to fixing that bug. It's a just a visual one, though, don't worry.

**Comment by neves768** [comment]
@mtadayz are you inspired? good to see u back

**Comment by mtadayz** [comment]
Fixed as of commit  5f60e0b.
