### ISSUE TITLE
PROBLEM IN LOGIN. Bind First Person "o"

### ISSUE THREAD

**Issue by godzera** [NullSystemWorks/mtadayz#157]
![mta-screen_2018-03-02_00-23-20](https://user-images.githubusercontent.com/36976165/36881993-0fc3c802-1db0-11e8-8a9f-4a83718ce912.png)
![Uploading mta-screen_2018-03-02_00-23-11.png…]()

**Comment by neves768** [comment]
@godzera Last update fixed it?
