### ISSUE TITLE
dublicate vehicle bug

### ISSUE THREAD

**Issue by ghost** [NullSystemWorks/mtadayz#160]
please fix bug dublicate vehicle https://prnt.sc/ipofb0

**Comment by mtadayz** [comment]
Page not found.

**Comment by Risusama** [comment]
Page not found, indeed. Seems like something sheibed something up while @No4NaMe was creating this issue. Here's the proper link, for an easier future:
https://prnt.sc/ipofb0

**Comment by mtadayz** [comment]
This happens because

a) Whenever you reset internal.db, the vehiclemanager will be deleted, which leads to
b) Vehicles "respawning" because they are saved in an extra database. 

I'll think of something that should prevent this.

**Comment by mtadayz** [comment]
Fixed as of commit  6c15361.
