### ISSUE TITLE
optimized and realistic clouds

### ISSUE THREAD

**Issue by ghost** [NullSystemWorks/mtadayz#166]
Hello all people, I have a code optimized and realistic clouds, they are incomparably incomparable. I can lay out the code, but if you add it to the mod and remove it too much?

this is not a script skybox 2.0 and 1.0!

https://prnt.sc/iv70gw
https://prnt.sc/iv723r
https://prnt.sc/iv720r
https://prnt.sc/iv71t6
https://prnt.sc/iv70gw

**Comment by mtadayz** [comment]
Please create a pull request if you think we should add that feature.
