### ISSUE TITLE
scoreboard

### ISSUE THREAD

**Issue by ghost** [NullSystemWorks/mtadayz#167]
Please add scoreboard, and time does not work in the game

**Comment by Risusama** [comment]
I highly doubt scoreboard will be added, as it has been removed a few commits ago.

**Comment by ghost** [comment]
how to see how many players are playing?

**Comment by mtadayz** [comment]
Adds immersion if you don't know how many players are on the server. Besides, if you're an admin, you can just check the admin panel. The scoreboard won't come back, unless by popular demand.
