### ISSUE TITLE
Scoreboard and Archievements dont work

### ISSUE THREAD

**Issue by MatiSrur** [NullSystemWorks/mtadayz#170]
In the scoreboard the people dont appear with any information. I try with other scoreboard but nothing.
And the Archievements the same thing.
I try everything but nothing. 
Help me please. Thank You

**Comment by 0xCiBeR** [comment]
Hi MatiSrur, support for this gamemode is currently at a halt. We are not actively developing the gamemode, but you are welcome to submit a pull request with the fix and we'll review it.

Thanks!
