### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by EduardoJGilA** [NullSystemWorks/mtadayz#171]
Can someone help me with dayz? I want to put more loot and vehicles, besides controlling the spawn of the zombies, please.
I'll put everything more explicit.
1. I would like to put more resources so that the players of my server (it is private) can not die so easily, I see that there is enough but I would like to put more and locate it.
2. I see very few vehicles, I would like to put more.
3. I would like the zombies not to appear in specific areas or that they are already in those zones, so they would not appear on the players' faces.
Sorry to use google translator.

**Comment by 0xCiBeR** [comment]
Hello. This issue page is for what the word says, submitting issues(problems) related to MTA:DayZ. We don't and won't support customization questions here. You can refer for community help to our discord: https://discord.gg/ubbR4UC
