### ISSUE TITLE
Vehicle Spawn - BUG

### ISSUE THREAD

**Issue by OllafLoten** [NullSystemWorks/mtadayz#172]
Well, gamemode itself works perfectly for me, but when I try to spawn vehicles using the Admin Panel (F7), I get the following error: "This feature is currently bugged!". How could I correct this "error"?

I already read a possible solution in the forum for this same problem, but realizing this suggestion caused an error in the console: "DayZ / init / vehicles / vehicles_init.lua: 266: bad argument # 1 to '[ipairs' nil) "

Could you tell me a possible solution? It would be a lot of help! Thank you very much.

* I'm using the "master" version.
* I did not change anything at all compared to the original scripts.
* I believe that many have encountered this same error, would be of great help if they could solve it.
*I'm sorry for my English.

**Comment by 0xCiBeR** [comment]
Hi Ollaf, support for this gamemode is currently at a halt. We are not actively developing the gamemode, but you are welcome to submit a pull request with the fix and we'll review it.

Thanks!
