### ISSUE TITLE
DayZ failed to link with ...

### ISSUE THREAD

**Issue by Phusion6** [NullSystemWorks/mtadayz#173]
I've tried setting up my dayz server recently and keep getting the same message over & over again when attempting to start the resource "dayz" it keeps saying 

"start: Resource 'dayz' start was requested (Failed to link to imageButton)" Or failed to link to slothbot and so on.

**Comment by 0xCiBeR** [comment]
Hi @Phusion6 . Do you have the mentioned resources in your resources folder?
