### ISSUE TITLE
Cannot take engine or tires off of vehicles. 

### ISSUE THREAD

**Issue by Risusama** [NullSystemWorks/mtadayz#179]
I've spent the last hour looking through commits, and I think I've narrowed the cause of it down to commit 9ca5de1.

In that commit,
file 'DayZ/gui/gear/ui_gear.lua' lines 123-125, function "getPlayerCurrentSlots" was changed to trigger a server event "onPlayerGetCurrentSlots", but the event itself is nowhere to be found.

This causes the error "Client triggered serverside event onPlayerGetCurrentSlots, but event is not added serverside" when trying to take engine or tire off of a vehicle, thus not proceeding with the action.

**Comment by mtadayz** [comment]
Fixed as of commit 954fa6b.
