### ISSUE TITLE
Make Box of Matches have a limited amount of matches

### ISSUE THREAD

**Issue by mtadayz** [NullSystemWorks/mtadayz#19]
Currently, Box of Matches have infinite matches, this should be changed. I propose adding a total usage limit of 6 times before this item disappears from the player's inventory.

**Comment by 0xCiBeR** [comment]
Agreed.

**Comment by 0xCiBeR** [comment]
Was thinking about this the other day. I think current system is just fine.. That said, if we still want this added we should get some feedback

**Comment by WyattParker** [comment]
On one hand, current system is fine, on the other hand, It wouldn't hurt anything. It would add "immersion" Matches are pretty common, at least on my server.

**Comment by mtadayz** [comment]
Not going to add this. They're not used very often, might as well leave them as they are.
