### ISSUE TITLE
Hunger/Thirst not decreasing

### ISSUE THREAD

**Issue by mtadayz** [NullSystemWorks/mtadayz#2]
Noticed it during my test runs, hunger and thirst are not decreasing in any way. I suspect this error to be the cause:

".../client/status_player.lua:673: attempt to perform arithmetic on field '?' (a boolean value)"

Currently tracking down the source of the bug, I suspect it has something to do with the clothes system.

**Comment by 0xCiBeR** [comment]
Welcome back L, we're on discord, join if you can

**Comment by 0xCiBeR** [comment]
ee6f9557a9115d256c7ae7793cabcd3b840591fa didn't seem to fix the problem acording to user reports @mtadayz

**Comment by mtadayz** [comment]
Any specific errors appearing? I tested my hunger and thirst using the DayZ admin panel, and it clearly decreased after certain actions (running, jumping, looting, etc).

**Comment by 0xCiBeR** [comment]
Can confirm it is working, though when difficulty is normal, it decreases to slow. Maybe some new values should be talked about there? Closing this issue anyway

**Comment by mtadayz** [comment]
Thing is, both parameters decrease according to your load, meaning how many items you have in your inventory. So if you're just testing around, without much gear, you won't notice a real difference, but if you're geared up, you'll need a lot of food and water to accomodate for that. Makes it a bit easier for newbies and a bit harder for veterans. However, I support adding an overall multiplier to the end value when increasing difficulty (since we already have normal, veteran and hardcore).
