### ISSUE TITLE
Randomize Loot Spawning Points

### ISSUE THREAD

**Issue by mtadayz** [NullSystemWorks/mtadayz#20]
There's over 2000(!) spawning points for loot, and those are just the default ones. Apply a random chance for each spawning point to make the map more varied and looting a "unique" experience every time loot is (re)spawned. Ideally, the max amount of loot points should be around half of the max. amount of spawning points.

Feedback is much appreciated on this issue.

**Comment by 0xCiBeR** [comment]
How would you calculate correctly spawn points without them going for example under ground? getGroundPosition is currently not working properly

**Comment by mtadayz** [comment]
Let me clarify that: we'll use the predetermined spawn points, we just make the chance for loot to appear a those spawnpoints in the first place random.

**Comment by mtadayz** [comment]
Loot spots now have a random chance to contain loot, depending on their buildingClass (for instance, lootpoints in the buildingClass "residential" have a value of 0.5 chance to contain loot, this is checked against a random value between 0.0 and 1.0).
