### ISSUE TITLE
Tear clothes up to receive bandages

### ISSUE THREAD

**Issue by mtadayz** [NullSystemWorks/mtadayz#23]
By rightclicking on a piece of cloth, then selecting "Tear cloth up", the player should be able to create bandages. Whether or not we introduce this as a new item ("Makeshift Bandage") or just let the player create a normal "Bandage" can be discussed here.

**Comment by 0xCiBeR** [comment]
Bumping this up, a normal bandage is ok

**Comment by Risusama** [comment]
I actually decided to make it - to my own surprise - and it works.
Here's a link to a demo, it's low quality video but that will have to do for now.
[DEMO](https://youtu.be/-CY9FH273hM)

Although, I had to make it use the items from the "newclothingsystem", so I still have to have figure out how to have the gamemode spawn the new clothing items even without the "newclothingsystem" being enabled. But other than that, the code is fully operational. (The "newclothingsystem" must be disabled for the option to "Tear cloth up" appear. I know it's not exactly what we wanted, but it is at least something. And people can always improve it if they'd like.)

I'm going to push at least the unfinished work to my repository in a few days/no later than tuesday after some more testing. (Got some unscheduled weekend trip to go to, so I didn't realize to push it before me and my family left.)

**Comment by Muurilo** [comment]
Good!

**Comment by Risusama** [comment]
YES! Figured out the last problem. My fork has been updated with the change and some typo fixes.

Enjoy!

**Comment by neves768** [comment]
Hey @DebexeL (Sir deberaa), thanks for your contribution. Can you create a pull request?

**Comment by Risusama** [comment]
@neves768 As you happened to ask that nicely, why not :P

**Comment by neves768** [comment]
#175 made it possible. Thanks @debexeL
