### ISSUE TITLE
Rework Zombie Spawning System

### ISSUE THREAD

**Issue by mtadayz** [NullSystemWorks/mtadayz#25]
The aim is to rework the current zombie spawn system.

Instead of letting zombies spawn every 3 seconds or so, they'll spawn at designated points, with a variable (gameplayVariables["maxglobalzombies"]) determining how many zombies can exist per world, to avoid putting too much strain on both client and server. 

My idea here is to let zombies spawn near lootpoints, to make them a bit more threatening (you want the loot, better find a way to avoid the zombies). Also, right now, when you crouch, zombies will instantly stop hunting you, and what's more, even if they do so much as touch you, nothing will happen as long as your visibility and audability value is 0. Perhaps a check to see if the zombie is within a certain distance to the Player (getDistanceBetweenPoints3D) might do the trick here.

Another problem is that zombies also will stop hunting you and go back to roaming mode when your audability value drops below a certain treshold. 

The file that handles this is movement_zombies.lua, which can be found in handlers/zombies/client.

This issue is an elaborated version of issue #18.

**Comment by mtadayz** [comment]
Update on this:

I'm working on it, and this is what I have so far:
- A second colsphere is created around lootspots
- When a player enters the second colsphere, zombies spawn

Current problems:
- Constantly re-entering the colsphere causes a shitload of zombies to spawn
- I don't know if those colspheres affect performance in any way (didn't for me)
- The current codes takes all players into account, meaning if player A enters the colsphere, zombies spawn, and if player B enters the same colsphere, more zombies spawn too

I'll keep y'all updated.

**Comment by 0xCiBeR** [comment]
I would max out zombies per colshape

**Comment by ghost** [comment]
How big is this colshape? Does the zombie pop up on your face? I guess it should look like it was already there.

**Comment by mtadayz** [comment]
The colsphere's size can be modified by server admins, the default value is 20m. No, they don't pop up on your face, they spawn around you, the radius being the colsphere size. 

@ciber96, good idea, will keep that in mind.

**Comment by mtadayz** [comment]
Has been added, experimental feature can be enabled in cfgServer (gameplayVariables["newzombiespawnsystem"]).

The new system works by creating a colsphere around loot, which determines the area zombies can spawn in. This is checked against a chance for each buildingType (usually somewhere between 0.3 and 0.4). This prevents too many zombies from spawning. Another safety check is the colsphere ID - if the ID matches the old one, zombies won't spawn, too. And finally, if a certain treshold (maxzombiesglobal) is reached, zombies won't spawn at all, unless some zombies despawn/are killed.

Feedback is much appreciated here!
