### ISSUE TITLE
Toggleable option for spawn selection

### ISSUE THREAD

**Issue by mtadayz** [NullSystemWorks/mtadayz#27]
Can be toggled by server admins. Make it a bit fancy, though, something like this:
http://se1.dayz.nu/latest/Images/687474703a2f2f692e696d6775722e636f6d2f45714b57446c622e6a7067.jpeg

**Comment by 0xCiBeR** [comment]
I guess random spawn points would be best.

**Comment by dreezyduh** [comment]
I also think that a lot of random spawn points should fix the camp problem

**Comment by mtadayz** [comment]
I'm not saying this'll be the new spawn system. It's something a server admin can decide on whether he wants to enable it or not. If enabled, the player will spawn in random locations which are around the area he selected (meaning if he selects Las Venturas, he'll spawn somewhere in Las Venturas). Makes spawn kills a bit less common, I hope.

**Comment by 0xCiBeR** [comment]
We could make a server config with a table with allowed zone spawns for example:
`gameServerVariables['allowedSpawn'] = { "Las Venturas", "Los Santos", "San Fierro"}`
And then just loop through and pick up a random spawn from a table correspondig to that zone.

**Comment by mtadayz** [comment]
Yep, that's the plan.

**Comment by mtadayz** [comment]
Spawnpoints can be now selected when the option is enabled in cfgServer (gameplayVariables["spawnselection"]. Moving the over ??? and clicking on it will result in your spawnpoint being random, while clicking on a photo will spawn you somewhere around that area. Also, new spawnpoints have been added.
