### ISSUE TITLE
Sniping a helicopter once makes it instantly explode

### ISSUE THREAD

**Issue by dreezyduh** [NullSystemWorks/mtadayz#31]
I don't think that this should be possible

**Comment by dreezyduh** [comment]
I don't think that this should be possible

**Comment by mtadayz** [comment]
Can you provide more information, like what kind of helicopter, how much health the heli had left at the time of the sniping, etc?

**Comment by dreezyduh** [comment]
My friends had 2 freshly spawned helicopters ( a sparrow and a maverick) with no trace of any kind of damage and it just took just one bullet from a DMR to start burning

**Comment by 0xCiBeR** [comment]
Can you please replicate the issue and while in vehicle check current health? Also if there is any debugs please post them!

**Comment by dreezyduh** [comment]
Nvm, it is working now, I don't know why . It maybe was because of the vehicles stacking on each other
