### ISSUE TITLE
Vehicle stack on server restart 

### ISSUE THREAD

**Issue by dreezyduh** [NullSystemWorks/mtadayz#32]
Pic https://imgur.com/Blt0aoq
Sometimes they bug and just explode

**Comment by mtadayz** [comment]
Can confirm this happening during my tests. I think I know why it's happening, have to make sure, though.

EDIT:
Found the source of this bug, need confirmation on it having been fixed. For that, you have to
- delete vehicles.db inside the databases folder
- stop DayZ, delete vehicleManager from the console (delaccount vehicleManager), then start DayZ again.

**Comment by dreezyduh** [comment]
Will test tomorrow

**Comment by GribixTugaZ** [comment]
Should i delete de vehicles.db before starting the server?Gonna test it now.Will confirm once i end the testing.

**Comment by mtadayz** [comment]
You have to delete it (and the vehicleManager) before starting DayZ

**Comment by dreezyduh** [comment]
I've played for around 2 hrs  and restarted for 5 times and no double vehicles at all

**Comment by mtadayz** [comment]
So we can consider this bug fixed?

**Comment by dreezyduh** [comment]
Yep
