### ISSUE TITLE
1 ms stutter every 1 sec

### ISSUE THREAD

**Issue by dreezyduh** [NullSystemWorks/mtadayz#36]
I don't know if anyone else has this problem but I'd like to know what could cause this problem

**Comment by 1B0Y** [comment]
Can you please tell us which MTA DayZ version you are using? If you're using an outdated MTA DayZ, please upgrade to the latest one also.

**Comment by dreezyduh** [comment]
I have the latest version but after playing for some time It starts stuttering,my friends are saying that they have no problem, might this be because I host it on my pc ?

**Comment by mtadayz** [comment]
Don't think so, I'm testing lots of stuff on my laptop, and I never really noticed any lag (and trust me, I'm testing under extreme conditions). How do you notice your game is stuttering?

**Comment by dreezyduh** [comment]
Well I first noticed this while driving a car and my friends could tell that as well because the car was stopping and moving again. I think It might have something to do with my windows. Anyway I'll just reinstall everything to make sure that it's not the game.

**Comment by mtadayz** [comment]
Was it only stuttering when you were inside a vehicle?

**Comment by dreezyduh** [comment]
Nope, it was stuttering all the time but only after I've played for some time and it seemed like a timer but I guess it's just my windows.

**Comment by 1B0Y** [comment]
Let us know how the gamemode is after reinstalling windows. Possible caching problem from an older version? We'll have to find out.

**Comment by dreezyduh** [comment]
After redownloading everything it finally runs well. Anyway as long as it would be me stuttering and no one else I'll be happy with it.
