### ISSUE TITLE
New debug monitor

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#39]
I just downloaded the newest version of the mod and soon realized that you guys have changed the debug monitor.I can understand why you guys did it.However,in my opinion,it wasn't a very good change.It's just not convenient for the player.If a player is getting hit by a zombie and wants to check his blood easily and fast without the need to stop,he can't do that now.
My  suggestion would be to add some kind of option to the player itself or even to the owner of the server to give the 2 options.If the player wants the old one,then enable the old one and vice versa.

**Comment by neves768** [comment]
or/and add keybind (shortcut) F5 to Debug page of Journal.

**Comment by 1B0Y** [comment]
or just have a command available to display the old debug monitor. It's what we did for Arma 2 DayZ when the DayZ creator removed the debug monitor entirely from the mod.

**Comment by mtadayz** [comment]
Check Issue #17 for more information.

Also, the reason I removed the debug monitor that, while it's certainly convenient, is that people entirely relied on it for information, neglecting the icons and the journal. And yeah, if a player has been hit by a zombie, then he should get the hell out of there, to a safe place, then tend to his wounds. You can still check your blood by looking at the icon (which, by the way, displays if you are infected, too).

**Comment by GribixTugaZ** [comment]
Honestly didn't even looked at the icons as i'm so used to play with the debug monitor.Now that you've cleared that up it makes more sense. I would still say that maybe adding a command like neves said would be a nice idea. Either way,it's nice the way it is.

**Comment by 1B0Y** [comment]
Re-introduced in 7809c1f with configuration options available for the server owners to toggle Debug Monitor abilities.
