### ISSUE TITLE
Fuel stations: limited fuel 

### ISSUE THREAD

**Issue by mtadayz** [NullSystemWorks/mtadayz#4]
Fuel stations should have limited fuel (to prevent people from just camping them out). The max amount can be set by server admins.

**Comment by 1B0Y** [comment]
If you reference the script which is responsible for creating fuel stations, I can add this functionality in

**Comment by mtadayz** [comment]
It's other_loot.lua in init/loot (all the way down) and sidemenu_gear.lua in gui/gear, beginning with the line "if itemName == "patrolstation" then [...]".

**Comment by 1B0Y** [comment]
Thanks. I'll have a look at it either tonight when I get home or tomorrow morning.

**Comment by 1B0Y** [comment]
Introduced in f97aa9508af4f577c40cf6a104faab6ac034fcea
