### ISSUE TITLE
DMR sound range to be increased.

### ISSUE THREAD

**Issue by 1B0Y** [NullSystemWorks/mtadayz#40]
While rewriting the sounds functionality for weapons, I noticed that the DMR has a range of 5 compared to other snipers that are 240. However, in my opinion, the DMR is just as loud as the other snipers...

Opinions?

**Comment by mtadayz** [comment]
The DMR is silenced, that's the reason its sound value is so low. The firing soundclip is kind of outdated, though, since it still plays a rather loud one. Might want to change that to a suppressed firing sound.

**Comment by 1B0Y** [comment]
DMR in DayZ Arma and Standalone aren't silenced, hence why the confusion

**Comment by mtadayz** [comment]
Yeah, I know. I based that decision back then mainly on the fact that the model has a silencer attached to it.

**Comment by 1B0Y** [comment]
I'll add an option in configs for the server owners to choose if the DMRs are silenced or not.

**Comment by 1B0Y** [comment]
Added in 48f3b13.
