### ISSUE TITLE
GPS system

### ISSUE THREAD

**Issue by Naturliskipsius** [NullSystemWorks/mtadayz#42]
Hi i want ask can you change GPS system like in old one version ? because its annyoing when you need write /gps and that arma 2 gps looks so bad

**Comment by mtadayz** [comment]
Bind the command to a key, that'll get rid of the annoyance. As for the "it looks bad" part, well that's unfortunately quite subjective. If you don't like it, feel free to change it. The gamemode is open source for a reason.

**Comment by 1B0Y** [comment]
We should probably bind GPS tbh. Ctrl + M was the bind for GPS in Arma. Maybe we should do the same?

**Comment by mtadayz** [comment]
Sure, why not?

**Comment by Naturliskipsius** [comment]
I dont want create new topic then i write here i want ask now default skin is cj i want ask how can i make random skins for all people ?

**Comment by mtadayz** [comment]
Binds have been added for both GPS and compass with commit ebe119f.
