### ISSUE TITLE
First person camera lets you turn only 180* in a fixed direction

### ISSUE THREAD

**Issue by dreezyduh** [NullSystemWorks/mtadayz#46]

**Comment by mtadayz** [comment]
Yep, that's kind of intentional, since you can't just rotate your head 360° either. I haven't gotten around to adding player rotation to it, so if you want to look into a new direction, you have to get out of first person mode first. So it's not a bug per se, more like an unfinished feature.

**Comment by dreezyduh** [comment]
Yea but the problem is that no matter where you want to  change your direction to , you will be stuck in the same direction.

**Comment by mtadayz** [comment]
I've added an emergency fix of sorts, you can now turn your head 360° when in first person mode. This should do the trick, for now, although you can't aim while in that mode.
