### ISSUE TITLE
Player spawn items

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#47]
How can i make a player spawn with a parachute already equipped?I've already added the parachute to the inventory.I would like to change it and make it so that the player spawns with the parachute already on his back and ready to use without the need of equipping in via inventory.

**Comment by mtadayz** [comment]
Edit playerDataTable. The first value is the item name, while the second one indicates how many items the player should possess in his inventory when the first spawns/respawns after death. However, keep in mind that this doesn't apply to already existing accounts, just for either newly registered ones or those who have died at least once after your edit.
