### ISSUE TITLE
Player Skins

### ISSUE THREAD

**Issue by Naturliskipsius** [NullSystemWorks/mtadayz#48]
i want ask can you add more random skins because now players spawn with the same skin or maybe add in login panel choose skins like or clothes something like that ? or you can make lesson how to do it ? Because like i told everyone spawns with CJ skin

**Comment by mtadayz** [comment]
Yeah, that's because of the clothes system. While everybody spawns as CJ, you have the option to change your clothes by looting some. However, I guess we can kind of randomize what kind of clothes you spawn with.

**Comment by mtadayz** [comment]
Added random clothes when a player registers an account and spawns or respawns after death.
