### ISSUE TITLE
Bug with spawn point choose

### ISSUE THREAD

**Issue by Naturliskipsius** [NullSystemWorks/mtadayz#49]
I found bug with spawn selector

Now when player dies spawn selector appears for everyone in the server

**Comment by mtadayz** [comment]
Should be fixed with commit b253918, need confirmation for it, though.

**Comment by Naturliskipsius** [comment]
Yes it works now perfectly :)

**Comment by Naturliskipsius** [comment]
If you need check updates online i have VPS  which i dont use
Skype: greenhunterltu
gmail greenhunterltu@hotmail.com
