### ISSUE TITLE
Helicrash with no model

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#50]
Pictures and explanation of how to reproduce the bugs are on the following link:

http://imgur.com/a/mFEHB

**Comment by mtadayz** [comment]
Getting a 404 error here.

**Comment by mtadayz** [comment]
Any updates on this?

**Comment by 0xCiBeR** [comment]
@GribixTugaZ any updates on this?

**Comment by mtadayz** [comment]
Since this issue seems to be floating in the air, with no update, I'll mark this as solved.
