### ISSUE TITLE
Cadency of weapons

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#52]
Is there anyway i can change the cadency of the weapons?I wanna change the cadency of fire of snipers.Wanna make them bolt action.Wanna make it so that the player has to wait like 2 seconds before shooting again.

**Comment by mtadayz** [comment]
Uh, yeah, it is possible, but that's actually something you'd have to discuss at the MTA forum, not here. We're just responsible for everything DayZ (although I admit your question kind of overlaps with our work).

Anyway, if you wish to add a fire latency (cadency doesn't even exist as word, by the way), go to handlers/players/client/damage_player.lua, and scroll down to the end. You'll find a function there called "weaponBurstFire", which you can edit to match your idea.
