### ISSUE TITLE
How to start vehicle respawn?

### ISSUE THREAD

**Issue by kerezsi1996** [NullSystemWorks/mtadayz#53]
Please write me command...

**Comment by mtadayz** [comment]
There's no command to respawn vehicles, unfortunately. However, I suppose we could add one.

**Comment by 0xCiBeR** [comment]
Would be a great idea. The thing is, if we do add it, all server vehicles will be respawned, even those that players moved for example in their base.

**Comment by ghost** [comment]
@ciber96, how about respawning only blown or sunk vehicles?

**Comment by Risusama** [comment]
@expert975 @ciber96 I'd like to try to add this. Can't promise it will be quick to make for me, but I would like to try. :) I'll inform you here if I ragequit from doing it, okay? :)

**Comment by ghost** [comment]
@DebexeL Sure! You can ask me if you need any help.

**Comment by 1B0Y** [comment]
Feature added. Check reference above for info.
