### ISSUE TITLE
Weapon skin

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#54]
How can i change a weapon skin?The weapon : M16A2 M203 has no skin so i want to add one.
I've already downloaded the files and put the dff and txd in the respective folders (resources\DayZ\models\weapons)

**Comment by mtadayz** [comment]
Is it in your meta.xml?

**Comment by GribixTugaZ** [comment]
I'm sorry i forgot to close this question.The problem has now been solved.
