### ISSUE TITLE
M40A3 sound

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#55]
I cant seem to put the M40A3 with sound.What do i exactly need to do?I've already copied the audio file to:
DayZ\sounds\weapons\fire and added the code in the sounds.lua file.Still not working.Am i missing something?

**Comment by 1B0Y** [comment]
Make sure that you add it to the weaponSounds table in sounds/sounds.lua near the bottom. Syntax:
["WEPNAME"] = {SOUND_DISTANCE,GUN_SOUND_FILE}

**Comment by GribixTugaZ** [comment]
This is the code i have in the local weaponSounds

["M40A3"] = {240,":DayZ/sounds/weapons/fire/M40A3.wav"},

Still doesn't seem to be working.

**Comment by mtadayz** [comment]
Have you made sure it's in the meta.xml of DayZ? /debugscript 3 may help locating the source of your alleged bug.

**Comment by GribixTugaZ** [comment]
Allright.Problem solved.Just had to add it to the meta.xml. Thanks for the help. Appreciate it :)!
