### ISSUE TITLE
MtaDayz- gliches

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [NullSystemWorks/mtadayz#56]
1. Zombies spawn near players, (falling from the sky, near players)! Even on respawn points
2. Drop/Take function is a little confusing for new players! And many stuff Have no texture dropped
3. F5 menu does not work, please tell me how i enamble it !

Tweaks! Zombies should spawn 10-20 feets away from players (minimum range)

//Using latest, stable  build :D.

**Comment by mtadayz** [comment]
1. The current zombie spawn system spawns zombies based on the material ID the player is walking on, that's why they may spawn near respawn points.
2. It may a bit confusing, but after 10 minutes, you (usually) get the hang of it. 
3. What F5 menu?

**Comment by TDMidkwhatisxd** [comment]
I dont use the mod anymore but!
F5 menu is were u can see, more stuff! Check dayz ultimate mta servers!
1.There are textures mising for some droped items!
2.Anti-Cheat detected me wen equiped a backpack (it made me give up)
3. Zombies should spawn only in cityes or near loot, not everywere in your face!
4. Map is weird!
5. Compass does not work!
6. Cant craft logs, nails and other stuff to make materials for a base!
7. Few cars are spawning
8. I dont see icon for humanity status!
//You should add this -> Ocasionaly, repaired cars should spawn, but damaged (2-3 crashes and boom)!//

I dont use this mod anymore, but i still wish u all good luck!

**Comment by mtadayz** [comment]
1. Need screenshots to confirm this bug.
2. Have you modified the backpacks, per chance?
3. Yup, that's in the works.
4. Noted.
5. It does.
6. You have to find them. They can be found in industrial areas.
7. Yeah, right, because we totally need 150+ vehicles. Edit the spawnpoints yourself if you want more cars.
8. Has been removed with the latest update.
9. Cars already respawn with variable health.

**Comment by ghost** [comment]
Can we have a screenshot with the missing textures?

**Comment by TDMidkwhatisxd** [comment]
Sorry, i just dont use the mod anymore ;-; !  
I didnt edit backpacks, just slots! 

I gave up on MtaSa server! I just wanted to report some stuff!
Your reply was too late, :D. The textures was like , dang i cant remember! Like  this [] , a little big, and looked like some stuff from pharmacy ( and it was the texture for clothes, weird xd).

**Comment by ghost** [comment]
The backpack textures are shown based on the number of slots.
Hard to fix if we don't know which texture is missing.

**Comment by 0xCiBeR** [comment]
If you modify your slots you have to modify the server variable security in charge of setting max slots for the server. If you overpass that var, you'll get picked up by the anticheat
