### ISSUE TITLE
Register isn't working, database

### ISSUE THREAD

**Issue by slavenx** [NullSystemWorks/mtadayz#58]
(sorry for my english)
Hi, I have a question, register isn't working, I added the most important lines to acl. And what i have to add to mysql?

**Comment by mtadayz** [comment]
Nothing, actually. Any errors appearing on the server console/in the server logs?

**Comment by 0xCiBeR** [comment]
MTA:DayZ doesn't use MySQL at the moment. It uses SQLite and all the tables needed are either provided or created on launch. You need to add login and dayz to the acl.

**Comment by GribixTugaZ** [comment]
I'm having the same problem.Recently i rented a server to host my MTA DayZ server using this core.I have everything has i have locally on my pc.Locally everything runs super smooth.The problem is that on my server it doesn't.Here are  the console logs everytime i click on the register button after fullfilling the account info.

http://i.imgur.com/NwsvKpG.png

**Comment by mtadayz** [comment]
It clearly states that the "login" resource is unable to use certain functions. You need to add it to the ACL, just like DayZ. For that, you have to stop the server first, because the ACL is reloaded to its former state whenever you edit it while the server is running.

**Comment by GribixTugaZ** [comment]
Thank you for the tip L! It's working now! Another problem has arrived tough.I can't open the admin panel.I receive the message telling me that to access the admin panel i need to click in "p".When i click it,nothing happens.Any way i can solve this problem?

**Comment by mtadayz** [comment]
Have you added yourself as an admin to the ACL? You need to add the name of your account to the ACL, not your player name.

**Comment by GribixTugaZ** [comment]
Yes.I can do all the things that only admins can do.The only thing that i can't is open the admin panel.

**Comment by GribixTugaZ** [comment]
Problem solved.Thanks for the help L!Appreciate it 👍 👍 💯
