### ISSUE TITLE
Help, Bugged TEXTURES?

### ISSUE THREAD

**Issue by ghost** [NullSystemWorks/mtadayz#62]
Good night!

In my **MTA DayZ Server** _(version 0.9.9)_ my friends can see the **world/map** normally but I can only see **solid colors**. Here are some prints..

Zombies:
![image](https://cloud.githubusercontent.com/assets/26886796/24637293/ea648ed0-18d7-11e7-96d7-6b361b48aec1.png)

Buildings:
![image](https://cloud.githubusercontent.com/assets/26886796/24637304/04466c60-18d8-11e7-881a-ad4ac5efa105.png)
![image](https://cloud.githubusercontent.com/assets/26886796/24637309/1177186c-18d8-11e7-849f-1df1f5e0c1e7.png)
![image](https://cloud.githubusercontent.com/assets/26886796/24637315/1e1f7a64-18d8-11e7-9679-0776cbb04e17.png)

Backpack & Weapon
![image](https://cloud.githubusercontent.com/assets/26886796/24637334/4152255e-18d8-11e7-87b9-aa3c47ed517b.png)

If I disable **DayZ resource** textures come back or if I use the **flashlight** I can see textures too..

Take ya' oldie **Chester** and go out there killin' sum _zambeis_!
**IkT.**

**Comment by mtadayz** [comment]
Think you can upload your clientscript.log somewhere? It's located inside MTA San Andreas 1.5/MTA/logs. I want to see if it's a clientsided problem.

**Comment by ghost** [comment]
Here you have it. :D 
[Clientscript.txt](https://github.com/ciber96/mtadayz/files/894089/Clientscript.txt)
Take ya' oldie **Chester** and go out there killin' sum _zambeis_!
**IkT.**

**Comment by mtadayz** [comment]
Had a look, and I can't seem to find anything that would point me to the source of this bug you are experiencing - which probably means it's something on your end, not DayZ. Have you tried another server to see if that bug persists?

**Comment by ghost** [comment]
Just entered another server and some things came back..
Some buildings had textures others did not.
Backpacks and weapons didn't have textures too..
I could not check cars like uaz.

Take ya' oldie **Chester** and go out there killin' sum _zambeis_!
**IkT.**

**Comment by mtadayz** [comment]
Well, it's definitely not a DayZ problem. Maybe you should head over to the MTA forum and ask there? Closing this.
