### ISSUE TITLE
Official MTA DayZ Server List

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#63]
Today i have launched my server using the gamemode developed here. How can i have my server in the official MTA DayZ server list? I will leave the ip adress of my server so that you guys can check it out and see if it has what it needs to be in the list.

Here's the server ip : 164.132.201.27:22033

**Comment by 0xCiBeR** [comment]
I'll be working later on this week to make a web visible Official server list. I'll discuss requirements for applying with the devs and let you know.

**Comment by 0xCiBeR** [comment]
https://master.mta-dayz.org/
