### ISSUE TITLE
Vehicle Parts!

### ISSUE THREAD

**Issue by ghost** [NullSystemWorks/mtadayz#65]
Hey there, there's an item called _Windscreen Glass_ but there's no vehicles using it?
**How to fix?**
Just change:
**MTA DayZ Server\server\mods\deathmatch\resources\DayZ\tables\table_vehicles** ?
Or is this a feature that will be implemented in future versions ?

Take ya' oldie **Chester** and go out there killin' sum _zambeis_!
**IkT.**

**Comment by mtadayz** [comment]
In older versions, that item was mandatory if you wanted to repair a vehicle. It's a bit of a leftover now, though. There's no need **fix** anything here. Altering the table won't really do it either, because there's no code that checks if the vehicle needs a Windscreen Glass, so I wouldn't bother.
