### ISSUE TITLE
Vehicles.

### ISSUE THREAD

**Issue by ghost** [NullSystemWorks/mtadayz#66]
Vehicles (like **sanchez** for **example**) tend to turn **on** when a **passenger** enters.
Can remove _engine & wheels_ but can't remove _rotary parts & tank parts_.
Also, **rotary parts not spawning** anywhere ?
Two **AN-2 bi-planes** spawning at the same spot (_house near the two bridges that connect SF to LV_) ?
**UAZ mod** makes the car **uncontrollable** (_suspension too high???_) ?

Take ya' oldie **Chester** and go out there killin' sum _zambeis_!
**IkT.**

**Comment by mtadayz** [comment]
1) Yeah, that's because of GTA's engine.
2) Could add that, I suppose.
3) They spawn. The chance is just quite low.
4) Probably an error on your server. Maybe the vehicles database happened to save them.
5) Yup. Don't be reckless.

**Comment by 1B0Y** [comment]
1. I'll look through to see if we have any existing code to add a check statement to turn the engine on/off when the passenger gets on.

**Comment by 1B0Y** [comment]
Added in 14cb80c9c28cc6626b99f4970487011f8b2503a4. Require feedback.

**Comment by 1B0Y** [comment]
Since no bug has been reported with the recent patch added a week ago, I'll go ahead and mark this as resolved.
