### ISSUE TITLE
Medic box 

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#69]
As you guys can see in the print,the medic box is in the wrong place.It should be in the floor,not on top of the building.
![mta-screen_2017-04-09_14-42-57](https://cloud.githubusercontent.com/assets/26173703/24837776/942d9a88-1d33-11e7-8888-7ccefcbc53e7.png)

**Comment by mtadayz** [comment]
What the hell...? How did that thing end up being there? I'll fix it as soon as I can.

**Comment by mtadayz** [comment]
Has been fixed.
