### ISSUE TITLE
Weapon skin bug

### ISSUE THREAD

**Issue by Kr3ptic** [NullSystemWorks/mtadayz#71]
I dont know if this is a bug or you guys made it like that but for example if you have 2 or more of the same kind of weapons like ak-74 and aks-74U it shows the original gta sa skin that happens with all the primary weapons the secondary weapons work fine

![mta-screen_2017-04-10_15-49-15](https://cloud.githubusercontent.com/assets/27247096/24885921/1428eec2-1e06-11e7-9c46-7ca3a84cac77.png)

even when you equip them its the same skin

**Comment by mtadayz** [comment]
It's not a bug per sé, it's because of the how the script loads the weapon skins. Since they're all clientsided, and only change when you have a particular weapon equipped, the bug you described above happens.
