### ISSUE TITLE
Car spawn in the middle of the road

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#75]
![mta-screen_2017-04-12_22-08-32](https://cloud.githubusercontent.com/assets/26173703/24979595/bd918b3c-1fcc-11e7-9a3e-9c2c6dd57ab3.png)
![mta-screen_2017-04-12_22-08-54](https://cloud.githubusercontent.com/assets/26173703/24979596/bdae1072-1fcc-11e7-9f8d-496af26d5537.png)

**Comment by mtadayz** [comment]
How is this a bug...?

**Comment by GribixTugaZ** [comment]
I reported this because i tought that this spawn wasn't meant to be here.If it's meant to be here then i'll close this issue.
