### ISSUE TITLE
Bug when throwing clothes to the ground that disappear.

### ISSUE THREAD

**Issue by PAXLv1** [NullSystemWorks/mtadayz#77]
Hi Guys, I think I found a bug and  wanted to know if anyone can help me.
When I throw some pants or clothes on the floor that disappears and I can not pick it up again

Image of debugscript error when i throw clothes to the ground.

Sorry for my english, I use the google translator.
![mta-screen_2017-04-16_22-35-12](https://cloud.githubusercontent.com/assets/27659112/25078043/043ab5f6-22f5-11e7-96cd-09b70804a904.png)

**Comment by mtadayz** [comment]
Fixed with latest commit (c5f3f67). Closing issue.
