### ISSUE TITLE
Globalchat not working

### ISSUE THREAD

**Issue by n1cfwe** [NullSystemWorks/mtadayz#79]
I installed the gamemode on my server and the globalchat does not work  i dont know what seems to be the problem

**Comment by Risusama** [comment]
Press X?
Sorry, but no one can help you if you just tell us "thing.xyz does not work".

**Comment by n1cfwe** [comment]
I pressed X and nothing happend .. the chatbox or whatever its called doesnt even show up.

**Comment by mtadayz** [comment]
1. Is the addon even active/has it been started?
2. Is the bind perhaps different?
3. Have you modified anything?

**Comment by n1cfwe** [comment]
I just found the problem thx for the responses.
