### ISSUE TITLE
Wrong map radar and compass

### ISSUE THREAD

**Issue by Fmd01** [NullSystemWorks/mtadayz#80]
Hello i downloaded this mod.IAt this mod the f11 map is(shit) i think and the radar and the compass too can i do with the normal map and radar?Help me how can i do that :D

**Comment by mtadayz** [comment]
hud_gear.lua is where the map and compass are coded. If you wish to change them, you have to do it yourself, we can't and won't provide in-depth guidelines for changing every little detail someone does not like.
