### ISSUE TITLE
Unconsciousness animation only visible by client

### ISSUE THREAD

**Issue by dreezyduh** [NullSystemWorks/mtadayz#9]

**Comment by 0xCiBeR** [comment]
I can confirm this.

**Comment by 1B0Y** [comment]
Which script is responsible for this, ciber?

**Comment by 1B0Y** [comment]
store achievements unlocked to a string using toJSON(), and send it to the server and store it to their account via setAccountData. To load the achievements, reverse it by getAccountData -> send to client -> fromJSON the string back into a table.

**Comment by mtadayz** [comment]
Think I fixed it, need someone to confirm it, though.

**Comment by dreezyduh** [comment]
It's fixed

**Comment by mtadayz** [comment]
Thanks, closing this issue.
