### ISSUE TITLE
Helmet bug

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#90]
The helmet doesn't show in player's head and the helmet icon still appears after player dies and respawns.

![helmet error](https://cloud.githubusercontent.com/assets/26173703/25586047/65bbfbf6-2e52-11e7-87ba-d25ee56023f1.png)

**Comment by 1B0Y** [comment]
On it!

**Comment by 1B0Y** [comment]
Need L's help with this. I don't have much knowledge with the inventory system.

**Comment by mtadayz** [comment]
Hopefully fixed with commit  6d851d6, need confirmation, though.

**Comment by GribixTugaZ** [comment]
It kinda fixed i think.Now no errors appear on the debugscript. Still.No helmet is showing in players head.

**Comment by mtadayz** [comment]
Are you using the classic skin system? Because the helmet icon appears as a substitute, since clothes can only be applied to the CJ skin.

**Comment by GribixTugaZ** [comment]
Yes i am. Imma change to the one that uses cj.Imma give some feedback when i have some news.

**Comment by GribixTugaZ** [comment]
Helmet does show in players head.No sign of helmet icon tough.
![mta-screen_2017-05-06_15-54-07](https://cloud.githubusercontent.com/assets/26173703/25773376/16512248-3231-11e7-977d-998c504c0c42.png)

**Comment by mtadayz** [comment]
Like I said, the icon is a substitute. It only appears when you are using the classic skin system.
