### ISSUE TITLE
Cache Validation

### ISSUE THREAD

**Issue by 1B0Y** [NullSystemWorks/mtadayz#91]
One of the main problems I've started noticing lately that server owners and players are starting to experience issues within the gamemode, which some is related to the caching of old scripts (either from other servers, or some problem with MTA's validation). Due to this, updating the gamemode will result in the player's cache corrupting (such as shaders not being loaded properly because it's from an older version).

To fix this, two steps need to be implemented:

- Added client and server versions, and do a check when the player joins to identify what version the client is running on.

- If the client is running an older version compared to the server version, the client's cache needs to be deleted entirely and then forced to redownload the server's version of the files. (Usually done via force-reconnecting the player to reinit the download).

**Comment by 0xCiBeR** [comment]
How are we on this? Maybe use MD5 checksums on files?

**Comment by 1B0Y** [comment]
I believe MTA eventually resolved this, so this can be closed.
