### ISSUE TITLE
Medic box in wrong position

### ISSUE THREAD

**Issue by GribixTugaZ** [NullSystemWorks/mtadayz#92]
![mta-screen_2017-05-03_21-27-01](https://cloud.githubusercontent.com/assets/26173703/25680001/33075c06-3004-11e7-988a-737797594ea6.png)

**Comment by 0xCiBeR** [comment]
Can i get the coords of the box?

**Comment by GribixTugaZ** [comment]
Whenever i get the time to i will fix it and pull request the fix.

**Comment by 0xCiBeR** [comment]
Any updates on this? Can i have the coords so i can push the fix?

**Comment by WyattParker** [comment]
This isn't happening on my server. It's in the right spot. From the looks of it, this is All Saints Hospital

**Comment by WyattParker** [comment]
Ok I found the coordinates that are causing it. I think each time the server starts, hospital boxes are shown randomly. These two coordinates put the boxes on the roof:
{1158.5048828125,-1326.333984375,31.503561019897},
{1159.80078125,-1323.9013671875,31.498970031738},

and yes, this is at All Saints Hospital in Los Santos

**Comment by WyattParker** [comment]
I've checked all of the coordinates, @ciber96 and apparently these weren't the only ones that were on the roof of the building. 
They're not entirely inaccessible, however, since Helicopters are available to be repaired. But if you'd like to remove the ones that are on the roof of the buildings, in DayZ/tables/table_general.lua  replace hospitalPacks table with this: 
```
`hospitalPacks = {
{-2670.87890625,636.8984375,14.453125},
{-2637.0556640625,635.03125,14.453125},
{-1515.669921875,2519.166015625,56.0703125},
{-1513.888671875,2519.5908203125,56.064819335938},
{-1528.8955078125,2516.724609375,55.986171722412},
{2022.1650390625,-1402.6806640625,17.18045425415},
{2042.7001953125,-1409.4775390625,17.1640625},
{-316.5478515625,1051.6494140625,20.340259552002},
{-337.9541015625,1049.490234375,19.739168167114},
{-323.2678330078,1052.5776367188,20.340259552002},
--[[{-307.0419921875,1045.27734375,26.012474060059},--]]
{-301.2462,1039.0581,19.7150},
{1171.490234375,-1310.560546875,13.986573219299},
{1171.609375,-1306.556640625,13.996350288391},
--[[{1158.5048828125,-1326.333984375,31.503561019897},
{1159.80078125,-1323.9013671875,31.498970031738},--]]
{1238.7119140625,328.2431640625,19.7555103302},
{1229.365234375,311.1435546875,24.7578125},
{-2204.07421875,-2309.58203125,31.375},
{1615.939453125,1818.0537109375,10.8203125},
{1601.9443359375,1816.736328125,10.8203125},
--[[{1590.0166015625,1792.0234375,30.46875},--]]
--[[{1607.3232421875,1776.7412109375,37.3125},--]]
--[[{2107.7626953125,926.16015625,10.8203125},--]]
--[[{2116.12890625,925.7705078125,10.9609375},--]]
--[[{2122.1865234375,925.3193359375,10.8203125},--]]
}`
```

All i did was comment out the coordinates that were on the roof.
Also, one thing I would like to mention, since this is 8 spots that are removed, in other_loot.lua, would the chance be slightly higher in the creation function, since less options are available?

**Comment by mtadayz** [comment]
These coordinates have never been touched by anyone, as far as I can remember. It's not entirely unfeasible to assume that the original author of the gamemode put them there for a reason. I wouldn't call this a bug per sé, more like "hard to reach unless you are airborne".

I think this can be safely closed.
