### ISSUE TITLE
Alguns problemas que encontrei

### ISSUE THREAD

**Issue by capivaracolha** [NullSystemWorks/mtadayz#97]
>FPS baixo, algo esta sugando o FPS
>As vezes o uso de medicamentos do inventario buga e nao cumpre o efeito (ex, painkiller usa mas nao para a dor)
>Skin da arma nas costas as vezes desaparece
>Lanterna quando esta equipada se efetuar um click, ela é "arremessada" e nao á como recuperar
>Debug f5 nao funciona/ debug lateral nao indica quanto blood o player tem

**Comment by capivaracolha** [comment]
continuando:
>servidor inicia com o gamemode "play" ativo
>foi alterado o nome dos veiculos porem ao entrar neles, ainda aparecem os originais

**Comment by neves768** [comment]
Can you write in English, please?
